### PR TITLE
Branch remove references to ab3

### LINKED ISSUE #81: Update all documentation to remove references to AB3
Currently, the documentation still reflect the name of Address Book 3. This issue aims to remove such references in preperation of PROperty's first product release.

### PR DESCRIPTION
**Pull request by Vatinius**
Resolves #81. In this PR, I aim to remove all references to AB3 and change them to PROperty instead. While I tried my best to be thorough, I may have missed out some areas, so do let me know if that is the case and I will resolve it ASAP.

### CODE REVIEW

**Review by Tkaixiang — COMMENTED** [review]
Would you like to consider changing the links in the `DeveloperGuide.md` as well?
https://github.com/Vatinius/tp/blob/046bea3cba4e492a85e76cdb2214f608be2d6f1c/docs/DeveloperGuide.md#L91-L92

**Comment by Vatinius** [comment]
> Would you like to consider changing the links in the `DeveloperGuide.md` as well? https://github.com/Vatinius/tp/blob/046bea3cba4e492a85e76cdb2214f608be2d6f1c/docs/DeveloperGuide.md#L91-L92

I did look through the `DeveloperGuide.md` and found that the links were still relevant, as it linked to [SE-EDU](https://se-education.org/), instead of explicitly AB3, and hence served to explain the logic of our address book to a potential developer.

But if there is a specific link/section that i missed out, do let me know!

**Comment by Tkaixiang** [comment]
> > Would you like to consider changing the links in the `DeveloperGuide.md` as well? https://github.com/Vatinius/tp/blob/046bea3cba4e492a85e76cdb2214f608be2d6f1c/docs/DeveloperGuide.md#L91-L92
> 
> I did look through the `DeveloperGuide.md` and found that the links were still relevant, as it linked to [SE-EDU](https://se-education.org/), instead of explicitly AB3, and hence served to explain the logic of our address book to a potential developer.
> 
> But if there is a specific link/section that i missed out, do let me know!

Ah, I am referring to links such as: (line 74)
```
The **API** of this component is specified in [`Ui.java`](https://github.com/se-edu/addressbook-level3/tree/master/src/main/java/seedu/address/ui/Ui.java)
```
Perhaps we could change them to our `Ui.java` instead

**Comment by Vatinius** [comment]
> > > Would you like to consider changing the links in the `DeveloperGuide.md` as well? https://github.com/Vatinius/tp/blob/046bea3cba4e492a85e76cdb2214f608be2d6f1c/docs/DeveloperGuide.md#L91-L92
> > 
> > 
> > I did look through the `DeveloperGuide.md` and found that the links were still relevant, as it linked to [SE-EDU](https://se-education.org/), instead of explicitly AB3, and hence served to explain the logic of our address book to a potential developer.
> > But if there is a specific link/section that i missed out, do let me know!
> 
> Ah, I am referring to links such as: (line 74)
> 
> ```
> The **API** of this component is specified in [`Ui.java`](https://github.com/se-edu/addressbook-level3/tree/master/src/main/java/seedu/address/ui/Ui.java)
> ```
> 
> Perhaps we could change them to our `Ui.java` instead

Ahh i see, didn't catch that one line. You make a good point; I'll get to it!

**Comment by Vatinius** [comment]
Changed all relevant hyperlinks to now link to PROperty's github repo instead.

**Review by Tkaixiang — APPROVED** [review]
lgtm

**Pull request merged**
