### PR TITLE
Implement export command

### LINKED ISSUE #179: Implement export command to PROperty
A user may want to export his current contacts into a Comma-Seperated Value (CSV) file to be viewed on other applications. This issue aims to implement an export command to solve this use-case.

### PR DESCRIPTION
**Pull request by Vatinius**
Resolves #179

### CODE REVIEW

**Review by tayxuenye — COMMENTED** [review]
I'm not sure if the command is supposed to download a csv file to my computer. As of now it doesn't do that and only says "Address book data has been exported!".

**Comment by Vatinius** [comment]
> I'm not sure if the command is supposed to download a csv file to my computer. As of now it doesn't do that and only says "Address book data has been exported!".

Could you check your `data` folder that contains the addressbook.json save folder? It should be there.

**Comment by tayxuenye** [comment]
> > I'm not sure if the command is supposed to download a csv file to my computer. As of now it doesn't do that and only says "Address book data has been exported!".
> 
> Could you check your `data` folder that contains the addressbook.json save? It should be there.

Yes there's a property.csv there. So it will be downloaded onto user's computer when it becomes a JAR file?

**Review by BuffWuff1712 — COMMENTED** [review]
Perhaps we could also tell the users where to find their exported CSV file in the help menu + user-guide?

**Comment by Vatinius** [comment]
> > > I'm not sure if the command is supposed to download a csv file to my computer. As of now it doesn't do that and only says "Address book data has been exported!".
> > 
> > 
> > Could you check your `data` folder that contains the addressbook.json save? It should be there.
> 
> Yes there's a property.csv there. So it will be downloaded onto user's computer when it becomes a JAR file?

Yep, it should act this way as well. But do give it a test just in case, as it works for me.

**Comment by Vatinius** [comment]
> Perhaps we could also tell the users where to find their exported CSV file in the help menu + user-guide?

Good idea. I'll write that in.

**Comment by tayxuenye** [comment]
> > > > I'm not sure if the command is supposed to download a csv file to my computer. As of now it doesn't do that and only says "Address book data has been exported!".
> > > 
> > > 
> > > Could you check your `data` folder that contains the addressbook.json save? It should be there.
> > 
> > 
> > Yes there's a property.csv there. So it will be downloaded onto user's computer when it becomes a JAR file?
> 
> Yep, it should act this way as well; it works for me. But do give it a test by launching it via a JAR file in a seperate folder just in case.

I exported to jar file and tested in a separate folder. No file is downloaded when I use the export command though.

**Comment by Vatinius** [comment]
> > > > > I'm not sure if the command is supposed to download a csv file to my computer. As of now it doesn't do that and only says "Address book data has been exported!".
> > > > 
> > > > 
> > > > Could you check your `data` folder that contains the addressbook.json save? It should be there.
> > > 
> > > 
> > > Yes there's a property.csv there. So it will be downloaded onto user's computer when it becomes a JAR file?
> > 
> > 
> > Yep, it should act this way as well; it works for me. But do give it a test by launching it via a JAR file in a seperate folder just in case.
> 
> I exported to jar file and tested in a separate folder. No file is downloaded when I use the export command though.

Could you screenshot the contents of your "Data" folder? Mine looks like this when I do the command using the JAR file
image

**Comment by Vatinius** [comment]
> Perhaps we could also tell the users where to find their exported CSV file in the help menu + user-guide?

Alright, I've put that in already! Additionally, could you help me check if you are able to see the exported .csv file under the "data" folder when you run the JAR file of PROperty?

**Comment by tayxuenye** [comment]
> > > > > > I'm not sure if the command is supposed to download a csv file to my computer. As of now it doesn't do that and only says "Address book data has been exported!".
> > > > > 
> > > > > 
> > > > > Could you check your `data` folder that contains the addressbook.json save? It should be there.
> > > > 
> > > > 
> > > > Yes there's a property.csv there. So it will be downloaded onto user's computer when it becomes a JAR file?
> > > 
> > > 
> > > Yep, it should act this way as well; it works for me. But do give it a test by launching it via a JAR file in a seperate folder just in case.
> > 
> > 
> > I exported to jar file and tested in a separate folder. No file is downloaded when I use the export command though.
> 
> Could you screenshot the contents of your "Data" folder? Mine looks like this when I do the command using the JAR file image

image

**Comment by Vatinius** [comment]
> > > > > > > I'm not sure if the command is supposed to download a csv file to my computer. As of now it doesn't do that and only says "Address book data has been exported!".
> > > > > > 
> > > > > > 
> > > > > > Could you check your `data` folder that contains the addressbook.json save? It should be there.
> > > > > 
> > > > > 
> > > > > Yes there's a property.csv there. So it will be downloaded onto user's computer when it becomes a JAR file?
> > > > 
> > > > 
> > > > Yep, it should act this way as well; it works for me. But do give it a test by launching it via a JAR file in a seperate folder just in case.
> > > 
> > > 
> > > I exported to jar file and tested in a separate folder. No file is downloaded when I use the export command though.
> > 
> > 
> > Could you screenshot the contents of your "Data" folder? Mine looks like this when I do the command using the JAR file image
> 
> Here you go. The csv file does appear when I use "export". image

That's great! Could you also test by running rerunning the shadowjar command and then running the JAR file in a seperate folder just in case.

**Review by BuffWuff1712 — APPROVED** [review]
@Vatinius I justed tested the JAR file and the export command works too! Will approve this

**Pull request merged**
