### PR TITLE
Add autocomplete feature for command name

### LINKED ISSUE #98: Auto-Completion for Commands
Currently, users have to remember and type out the entire command name to execute it. As such, we propose to improve the user's experience, pressing [TAB] should be able to autocomplete the command name to a valid command name starting with the user's input if found.

Once the command has been autocompleted, there will be a space added to the end for the user to type the command arguments. If there is no command found, nothing will happen.

### PR DESCRIPTION
**Pull request by sayomaki**
Resolves #98. 

This PR adds a new feature to allow users to auto-complete the command name input for any valid commands, and users will only need to key in the first (or few) characters of the command name, and pressing [TAB] will fill in the remaining characters that make up the command word.

### CODE REVIEW

**Comment by Tkaixiang** [comment]
I am not sure if this is supposed to happen, but typing `fi` and pressing [TAB] autocompletes it to `findtag` instead of `find`

**Review by Tkaixiang — APPROVED** [review]
lgtm

**Comment by Vatinius** [comment]
I noticed typing `listing a` and pressing [TAB] does not auto complete to `listing add`. The same goes for the `listing delete` too. 

Otherwise, lgtm!

**Review by tayxuenye — APPROVED** [review]
I'm not sure if this is what you intended but typing li gives listing instead of list and typing fi gives findtag instead of find. If we don't want this to be counted as a bug I feel it's best to indicate that this is an intended behaviour in the documentation.

**Comment by sayomaki** [comment]
> I noticed typing listing a and pressing [TAB]

The listing command has subcommands which is not handled in this case, and this is the only command that uses subcommands.

**Pull request merged**
